### ISSUE TITLE
Add todo and contributing for this project

### ISSUE THREAD

**Issue by kevin-schmitt** [somewhatabstract/ancesdir#202]
Hello,

Thanks for this project.
I think is interesting for possible new contributors, to add todo with possible features and contribution (for, branch name, workflow). It's possible please?

**Comment by somewhatabstract** [comment]
Thank you for your interest. Please see the [CONTRIBUTING.md](https://github.com/somewhatabstract/ancesdir/blob/master/CONTRIBUTING.md) doc.
Currently, there are no issues to work on for this library. It does everything it needs to at this time.
