### ISSUE TITLE
`ancesdir` doesn't find marker if it's the directory passed to `ancesdir()`

### ISSUE THREAD

**Issue by kevinbarabash** [somewhatabstract/ancesdir#910]
Calling `ancesdir(__dirname, ".marker")` fails if the `.marker` file is in `__dirname` and not an ancestor directory.

**To Reproduce**
1. Create marker file '.marker'
2. Import 'ancedir'
3. Call `ancesdir(__dirname, ".marker")` from a .js file in the same directory as `.marker`.

**Expected behavior**
It should return `__dirname`

**Actual behavior**
There's an error message about it not being able to find the "marker" file.

**Desktop (please complete the following information):**
 - OS: macOS
 - Node Version: 16.14.1
 - `ancesdir` Version 4.0.0

**Additional info**
I tried use `ancesdir(__dirname)` to see if it could find the package.json file that was in services/static/ in webapp, but it ended up returning the root path as well.

**Comment by somewhatabstract** [comment]
Yup, that's by design. It doesn't look in the same directory as the starting point. You can workaround this by extending the starting point with a subpath.
